import './globals.css'
import { Inter } from 'next/font/google'

// Components
import Login from './login';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/route';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next-Auth Firebase Adapter',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Login session={session} />
        {children}
      </body>
    </html>
  )
}
